# Generated by Django 2.2.5 on 2020-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
