# Generated by Django 2.2.5 on 2020-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200227_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
