# Generated by Django 2.2.5 on 2020-02-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200227_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='username',
            field=models.EmailField(max_length=200),
        ),
    ]
