# Generated by Django 2.2.5 on 2020-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200227_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_status',
            name='id',
        ),
        migrations.AddField(
            model_name='project_status',
            name='s_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project_status',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'APPROVED'), ('D', 'DECLINED'), ('C', 'COMPLETED')], default='P', max_length=1),
        ),
    ]
