# Generated by Django 2.2.5 on 2020-02-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200227_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_status',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='project_status',
            name='status',
        ),
        migrations.AddField(
            model_name='project_status',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[('Pending', 'PENDING'), ('Approved', 'APPROVED'), ('Declined', 'DECLINED'), ('Completed', 'COMPLETED')], default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.EmailField(max_length=150),
        ),
    ]
