# Generated by Django 2.2.5 on 2020-02-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200228_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_status',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[('Pending', 'PENDING'), ('Approved', 'APPROVED'), ('Declined', 'DECLINED'), ('Completed', 'COMPLETED')], default='Pending', primary_key=True, serialize=False),
        ),
    ]
