# Generated by Django 2.2.5 on 2020-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200228_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_status',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Approved', 'APPROVED'), ('Declined', 'DECLINED'), ('Completed', 'COMPLETED')], default='Pending', max_length=1),
        ),
        migrations.AlterField(
            model_name='project_status',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
