# Generated by Django 2.2.5 on 2020-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200228_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_status',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'APPROVED'), ('D', 'DECLINED'), ('C', 'COMPLETED')], default='Pending', max_length=1),
        ),
    ]
