# Generated by Django 2.2.5 on 2020-02-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker_status',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project_status',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='username',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
