# Generated by Django 2.2.5 on 2020-03-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200328_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_work_hours', models.PositiveIntegerField(default=0)),
                ('point_per_hour', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='myapp.Payment'),
        ),
    ]
