# Generated by Django 2.2.5 on 2020-03-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200329_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='point_per_hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment2', to='myapp.Project'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_work_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment1', to='myapp.Project'),
        ),
    ]
