# Generated by Django 2.2.5 on 2020-03-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20200329_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
