# Generated by Django 2.2.5 on 2020-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200329_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_work_hours', models.PositiveIntegerField(default=0)),
                ('point_per_hour', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
