# Generated by Django 2.2.5 on 2020-03-31 11:29

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20200331_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(validators=[myapp.models.validate_date_not_in_past], verbose_name='End Date* (YYYY-MM-DD)'),
        ),
    ]
