# Generated by Django 2.2.5 on 2020-03-31 11:34

from django.db import migrations, models
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20200331_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(validators=[myapp.models.validate_date_not_in_past], verbose_name='End Date* (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
