# Generated by Django 2.2.5 on 2020-03-31 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20200331_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
