# Generated by Django 2.2.5 on 2020-04-02 07:04

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, validators=[myapp.models.validate_date_not_in_past]),
        ),
    ]
