# Generated by Django 2.2.5 on 2020-04-02 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_auto_20200402_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 2, 3, 45, 42, 443460)),
        ),
    ]
