# Generated by Django 2.2.5 on 2020-04-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20200402_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='point_per_hour',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='myapp.Project_Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_work_hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
