# Generated by Django 2.2.5 on 2020-04-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_auto_20200402_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='point_per_hour',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_work_hours',
        ),
    ]
