# Generated by Django 2.2.5 on 2020-04-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_auto_20200402_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
