# Generated by Django 2.2.5 on 2020-04-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default='PENDING', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='myapp.Project_Status', to_field='status'),
        ),
        migrations.AlterField(
            model_name='project_status',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=20, unique=True),
        ),
    ]
