# Generated by Django 2.2.5 on 2020-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='point_per_hour',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='project',
            name='total_work_hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
