# Generated by Django 2.2.5 on 2020-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_auto_20200402_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker_Status',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=20, unique=True)),
            ],
        ),
    ]
