# Generated by Django 2.2.5 on 2020-04-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0060_worker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_status',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='myapp.Worker_Status')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_username', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
