# Generated by Django 2.2.5 on 2020-04-06 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_auto_20200406_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='application_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
