# Generated by Django 2.2.5 on 2020-04-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_worker_application_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker_Request',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_request', to='myapp.Project', to_field='title')),
            ],
        ),
    ]
